# Generated by Django 4.0.4 on 2022-05-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stati_Segnalazione',
            fields=[
                ('id_stato_segnalazione', models.IntegerField(primary_key=True, serialize=False)),
                ('stato_segnalazione', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stato_segnalazioni',
            },
        ),
        migrations.CreateModel(
            name='Stati_Soluzione',
            fields=[
                ('id_stato_soluzione', models.IntegerField(primary_key=True, serialize=False)),
                ('stato_soluzione', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stato_soluzioni',
            },
        ),
        migrations.CreateModel(
            name='Soluzioni',
            fields=[
                ('id_soluzione', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField()),
                ('descrizione', models.TextField()),
                ('immagine_1', models.TextField()),
                ('immagine_2', models.TextField()),
                ('immagine_3', models.TextField()),
                ('settore_riferimento', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_stato_soluzione', models.ForeignKey(blank=True, db_column='id_stato_soluzione', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.stati_soluzione')),
            ],
            options={
                'db_table': 'soluzioni',
            },
        ),
        migrations.CreateModel(
            name='Segnalazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_segnalazione', models.IntegerField()),
                ('titolo', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.TextField()),
                ('id_allarme', models.CharField(max_length=255)),
                ('descrizione_allarme', models.TextField()),
                ('famiglia_macchina', models.CharField(max_length=255)),
                ('sottofamiglia_macchina', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_stato_segnalazione', models.ForeignKey(blank=True, db_column='id_stato_segnalazione', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.stati_segnalazione')),
            ],
            options={
                'db_table': 'segnalazioni',
            },
        ),
        migrations.CreateModel(
            name='Occorrenze',
            fields=[
                ('id_occorrenza', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('commessa_macchina', models.CharField(max_length=255)),
                ('versione_sw_1', models.CharField(max_length=255)),
                ('versione_sw_2', models.CharField(max_length=255)),
                ('data_occorrenza', models.CharField(max_length=255)),
                ('stato_occorrenza', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.segnalazioni')),
                ('id_soluzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.soluzioni')),
            ],
            options={
                'db_table': 'occorrenze',
            },
        ),
    ]
