# Generated by Django 4.0.4 on 2022-05-25 13:50

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazioni',
            name='id_stato_segnalazione',
            field=models.ForeignKey(blank=True, db_column='id_stato_segnalazione', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.stati_segnalazione'),
        ),
        migrations.AlterField(
            model_name='soluzioni',
            name='immagine_1',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='soluzioni',
            name='immagine_2',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='soluzioni',
            name='immagine_3',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
    ]
