# Generated by Django 4.0.4 on 2022-05-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occorrenze',
            name='rif_ticket',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segnalazioni',
            name='rif_ticket',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segnalazioni',
            name='id_stato_segnalazione',
            field=models.ForeignKey(blank=True, db_column='id_stato_segnalazione', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.stati_segnalazione'),
        ),
    ]
