# Generated by Django 4.0.4 on 2022-05-27 08:09

from django.db import migrations, models

import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_segnalazioni_id_stato_segnalazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazioni',
            name='immagine_1',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
        migrations.AddField(
            model_name='segnalazioni',
            name='immagine_2',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
        migrations.AddField(
            model_name='segnalazioni',
            name='immagine_3',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
    ]
