# Generated by Django 4.0.4 on 2022-05-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_segnalazioni_immagine_1_segnalazioni_immagine_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occorrenze',
            name='soluzione',
        ),
        migrations.AddField(
            model_name='soluzioni',
            name='occorrenze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.occorrenze'),
        ),
    ]
