# Generated by Django 4.0.4 on 2022-05-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_occorrenze_segnalazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluzioni',
            name='occorrenze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soluzioni_id', to='mainapp.occorrenze'),
        ),
    ]
