# Generated by Django 4.0.4 on 2022-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_occorrenze_rif_ticket_segnalazioni_rif_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazioni',
            name='note',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
