# Generated by Django 4.0.4 on 2022-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_occorrenze_segnalazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occorrenze',
            name='commessa_macchina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
