# Generated by Django 4.0.4 on 2022-05-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_soluzioni_occorrenze'),
        ('mainapp', '0010_alter_occorrenze_commessa_macchina_and_more'),
    ]

    operations = [
    ]
