# Generated by Django 4.0.4 on 2022-06-01 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_occorrenze_commessa_macchina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occorrenze',
            name='commessa_macchina',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='descrizione',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='note',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 6, 1, 10, 34, 54, 638029)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='segnalazioni',
            name='descrizione',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='segnalazioni',
            name='descrizione_allarme',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='segnalazioni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 6, 1, 10, 35, 4, 958064)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soluzioni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 6, 1, 10, 35, 13, 653110)),
            preserve_default=False,
        ),
    ]
