# Generated by Django 4.0.4 on 2022-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20220531_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occorrenze',
            name='commessa_macchina',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='descrizione',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='versione_sw_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='segnalazioni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluzioni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stati_segnalazione',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stati_soluzione',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
