# Generated by Django 4.0.4 on 2022-06-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_occorrenze_commessa_macchina_and_more'),
        ('mainapp', '0012_alter_occorrenze_commessa_macchina_and_more'),
    ]

    operations = [
    ]
