# Generated by Django 4.0.4 on 2022-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_merge_20220613_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stati_segnalazione',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stati_soluzione',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
