# Generated by Django 4.0.4 on 2022-07-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_stati_segnalazione_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occorrenze',
            name='soluzione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soluzione', to='mainapp.soluzioni'),
        ),
    ]
