# Generated by Django 4.0.4 on 2022-07-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_occorrenze_soluzione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluzioni',
            name='occorrenze',
        ),
        migrations.AlterField(
            model_name='occorrenze',
            name='soluzione',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.soluzioni'),
        ),
    ]
