# Generated by Django 4.0.4 on 2022-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_soluzioni_occorrenze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occorrenze',
            name='soluzione',
            field=models.IntegerField(null=True),
        ),
    ]
