# Generated by Django 4.0.4 on 2022-07-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_occorrenze_soluzione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occorrenze',
            name='segnalazione',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.segnalazioni'),
        ),
    ]
