# Generated by Django 4.0.4 on 2022-05-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ModelHasRoles',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.roles')),
                ('model_type', models.CharField(max_length=255)),
                ('model_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'model_has_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleHasPermissions',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.permissions')),
            ],
            options={
                'db_table': 'role_has_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
                ('email', models.EmailField(default=None, max_length=60, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ModelHasPermissions',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.permissions')),
                ('model_type', models.CharField(max_length=255)),
                ('model_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'model_has_permissions',
                'unique_together': {('permission', 'model_id', 'model_type')},
            },
        ),
    ]
