# Generated by Django 4.0.4 on 2022-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
                ('username', models.CharField(default=None, max_length=255, unique=True)),
                ('email', models.EmailField(default=None, max_length=60, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
