# Generated by Django 4.0.4 on 2022-05-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_date_joined_users_first_name_users_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
