# Generated by Django 4.0.4 on 2022-05-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_users_date_joined_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permissions', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.RemoveField(
            model_name='modelhasroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolehaspermissions',
            name='permission',
        ),
        migrations.DeleteModel(
            name='ModelHasPermissions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='ModelHasRoles',
        ),
        migrations.DeleteModel(
            name='RoleHasPermissions',
        ),
        migrations.AlterField(
            model_name='users',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.userhaspermissions'),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
