# Generated by Django 4.0.4 on 2022-06-01 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_names_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 6, 1, 10, 45, 55, 233143)),
            preserve_default=False,
        ),
    ]
